require("ibl").setup({
  indent = {
    char = "▏",
  },
  scope = {
    enabled = false,
    show_start = true,
    show_end = false,
    injected_languages = false,
    highlight = { "Function", "Label" },
  },
  exclude = {
    filetypes = {
      "help",
      "terminal",
      "dashboard",
      "alpha",
      "packer",
      "lspinfo",
      "TelescopePrompt",
      "TelescopeResults",
      "startify",
      "dashboard",
      "dotooagenda",
      "log",
      "fugitive",
      "gitcommit",
      "packer",
      "vimwiki",
      "markdown",
      "txt",
      "vista",
      "help",
      "todoist",
      "NvimTree",
      "peekaboo",
      "git",
      "TelescopePrompt",
      "undotree",
      "flutterToolsOutline",
      "lsp-installer",
      "oil",
      "oil_preview",
      "qf",
      "bqfpreview",
      "",
    },
    buftypes = {
      "terminal",
    },
  },
})
